### ISSUE TITLE
Please identify your software when connecting to servers

### ISSUE THREAD

**Issue by kyuupichan** [monkeylord/MiniGate#1]
I think it currently identifies as "0".  How about identifying as "Minigate 0.1" or whatever the version number is?  It helps server operators know who's using the service and for what.

**Comment by kyuupichan** [comment]
Also you should connect for protocol 1.4; 1.2 is about to be dropped

**Comment by monkeylord** [comment]
Thank you.
I've forgot that.

**Comment by monkeylord** [comment]
Done.
MiniGate now identify itself as `MiniGate v${version}`

**Comment by kyuupichan** [comment]
Thanks.  Did you miss my 2nd message above, or is 1.2 required for some reason?

**Comment by monkeylord** [comment]
Yes, the 2nd message is ElectrumX Protocol Version.
It means I use electrumx 1.2 API.

**Comment by monkeylord** [comment]
I use `node-electrum-client` to connect electrumx server.
It use 1.2 protocol.

I need to do some test before upgrading to 1.4
